meta_product_name: "INA"
meta_title: "Holdina – Nagradni natjecaj – Natočite 20 litara Class Plus goriva na svim INA i Energopetrol maloprodajnim mjestima u FBiH od 01.12.2021. do 31.01.2022."
meta_description: "Natočite 20 litara Class Plus goriva na svim INA i Energopetrol maloprodajnim mjestima u FBiH od 01.12.2021. do 31.01.2022. godine, prijavite se i osvojite jednu od 180 vrijednih nagrada u gorivu ili automobil Golf 8!"
meta_image: "webanner.png" # should exist in `app/assets/images/`
